.SILENT:
.SUFFIXES:
ROOT=../site
.PRECIOUS: $(ROOT)/src/%.txt
TM=find 'clean(c)' 'realclean(r)' 'distclean(d)' 'status(s)'
TD=html
TR=
H=$(ROOT)/html
T=$(ROOT)/src
HTML=$H/Notes.html $H/index.html
TEXT=$T/Notes.txt $T/index.txt
default: echo
s:	status
c:	clean
d:	distclean
r:	realclean
echo:	find
	@echo "Targets:"
	@echo "	maintenance:	" $(TM)
	@echo "	deployment:	" $(TD)
	@echo "	removal:	" $(TR)
	@echo "	abbrevs:	 s='status', c='clean' etc"
find:
	@find .. \( -name '*.pyc' -o -name '*~' \)
clean:
	@find .. \( -name '*.pyc' -o -name '*~' \) -a -exec rm -f '{}' \;
status:	realclean
	@-git status
distclean:	realclean
	rm -rf $(ROOT)
realclean:	clean
../site:
	mkdir -p $(ROOT)/html
	mkdir $(ROOT)/src
site:	$(ROOT)
	@[ -d $(ROOT)/html ] || echo 'first make dirs'
	@[ -d $(ROOT)/html ] || exit -1
text:	site $(TEXT)
html:	$(HTML)
$T/%.txt:	%.eom
	eom ascii $< > $@
$H/%.html:	$T/%.txt
	awb ghawb

